services:
  web:
    build: .
    container_name: web
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/Task-managment
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres
    container_name: task_management_db
    volumes:
      - ./db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432

volumes:
  postgres_data: